"""Remove page_number from Book model

Revision ID: e113f7d88558
Revises: 
Create Date: 2024-12-07 14:37:00.299170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e113f7d88558'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('page_number')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('member_since')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_since', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_number', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
